[package]
name = "bingo/roblocks"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
matter = "evaera/matter@0.7.0"
rewire = "sayhisam1/rewire@0.3.0"
plasma = "evaera/plasma@0.4.2"
